name: First Pipeline

# Trigger: Run on every push to main branch
on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Get the repo code
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Print hello
      - name: Say Hello
        run: echo "Hello, GitHub Actions! My pipeline is working 🚀"
